### ISSUE TITLE
VSCode Command PSRule Run analysis not working

### ISSUE THREAD

**Issue by neok-g** [microsoft/PSRule-vscode#1276]
**Description of the issue**

The command PSRule Run analysis is not working.
The output window does not display any warnings or whatsoever.

**To Reproduce**

Steps to reproduce the issue:
- Running MacOS (Sonoma 14.1)
- Installed PowerShell 7.3.9
- Installed PowerShell PSRule 2.9.0
- Installed VSCode extension PSRule 2.9.0
- Run command PSRule Run analysis 

**Expected behaviour**

Would expect to see the PSRule warnings 

**Error output**

Capture any error messages and or terminal output.

None

**Extension version:**

- Version: 2.9.0

**PSRule module version: 

Captured output from `Get-InstalledModule PSRule | Format-List Name,Version`:

Name    : PSRule
Version : 2.9.0

**Additional context**

**Comment by BernieWhite** [comment]
@neok-g Are you choosing "PSRule: Run analysis" from the command palette or `Terminal` > `Run Task...`.

You are able to provide the output logs from `View` > `Output` select `PSRule`?

**Comment by neok-g** [comment]
@BernieWhite Sorry for the late response but the problem seems to be solved! Thanks anyway!
